# Generated by Django 2.2.6 on 2020-02-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artical',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='ArticalType',
            new_name='ArticleType',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='artical_type',
            new_name='article_type',
        ),
    ]
