# Generated by Django 2.2.6 on 2020-02-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200217_0730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleType',
            new_name='ArticalType',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_type',
            new_name='artical_type',
        ),
    ]
