# Generated by Django 2.2.6 on 2019-12-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
