# Generated by Django 2.2.6 on 2019-12-17 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='both'),
        ),
        migrations.AddField(
            model_name='host',
            name='port',
            field=models.IntegerField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Business'),
        ),
    ]
