# Generated by Django 2.2.6 on 2019-12-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191217_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='b',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
