# Generated by Django 2.2.6 on 2019-12-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_application_hosttoapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='r',
            field=models.ManyToManyField(to='app01.Host'),
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
