# Generated by Django 2.2.6 on 2019-12-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
