# Generated by Django 2.2.6 on 2019-12-15 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20191215_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.UserGroup'),
        ),
    ]
