# Generated by Django 2.2.6 on 2020-02-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.IntegerField(choices=[(1, 'python'), (2, 'linux'), (3, 'openstack')]),
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
    ]
