# Generated by Django 2.2.6 on 2020-02-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_article_article_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'python'), (2, 'linux'), (3, 'openstack')], default=1),
            preserve_default=False,
        ),
    ]
